### ISSUE TITLE
Publicly available game engine

### ISSUE THREAD

**Issue by KhanhNgoDuy** [foocker/F2P#10]
Hi, I was looking for a game engine suitable for generating the model as in the paper. However, the most similar one is Human Generator V4 in Blender, which costs $68. Do you have any recommendations for such game engine, or the one that you have used for this project?

**Comment by foocker** [comment]
> Hi, I was looking for a game engine suitable for generating the model as in the paper. However, the most similar one is Human Generator V4 in Blender, which costs $68. Do you have any recommendations for such game engine, or the one that you have used for this project?

no, i use engine is also from unity, it is simple(few bones to  drive ) and work bad.

**Comment by KhanhNgoDuy** [comment]
Can you share the link to the engine? Thank you!

**Comment by foocker** [comment]
> Can you share the link to the engine? Thank you!

maybe rewrite from the exist package. i just use it , not write it. maybe u can using `uma`
