### ISSUE TITLE
大哥 能不能写一个外行也能看懂过的README

### ISSUE THREAD

**Issue by sh308178685** [foocker/F2P#4]
大哥 能不能写一个外行也能看懂过的README

**Comment by sh308178685** [comment]
纯外行，想用这个训练一个UE5捏脸程序，输入图片，生成一组捏脸参数，

**Comment by foocker** [comment]
> 大哥 能不能写一个外行也能看懂过的README

没办法，对不同数据（捏脸数据格式不同），数据部分代码都要重写。能做这个，其他就都没问题了。

**Comment by sh308178685** [comment]
> > 大哥 能不能写一个外行也能看懂过的README
> 
> 没办法，对不同数据（捏脸数据格式不同），数据部分代码都要重写。能做这个，其他就都没问题了。

我已经修改了存档数据部分的代码 还是跑不通啊，少了好多东西，大哥 有没有联系方式啊 求指导

**Comment by foocker** [comment]
> > > 大哥 能不能写一个外行也能看懂过的README
> > 
> > 
> > 没办法，对不同数据（捏脸数据格式不同），数据部分代码都要重写。能做这个，其他就都没问题了。
> 
> 我已经修改了存档数据部分的代码 还是跑不通啊，少了好多东西，大哥 有没有联系方式啊 求指导

具体什么问题？

**Comment by hafewa** [comment]
能拉个群吗

**Comment by foocker** [comment]
> 能拉个群吗

具体啥问题，issue一条一条列出来就行。

**Comment by sh308178685** [comment]
> 出来就行。

1. 那个config里面貌似有三个流程？ I ,T, INFER,这三个分别是什么意思啊，执行顺序是什么
2. 我试了I T 都跑不通会报错。config。yaml task: I 报错：
![image](https://github.com/foocker/F2P/assets/5687816/aba7f054-f6c1-4a3a-8986-ad1befc4807b)   
task: T 报错 
![image](https://github.com/foocker/F2P/assets/5687816/3d2b8d58-63f7-4bb5-983c-186b5ede4230)
好像少了一个文件啊，这个不是checkpoint吗 我第一次运行为什么需要这个

**Comment by sh308178685** [comment]
> > 出来就行。
> 
> 1. 那个config里面貌似有三个流程？ I ,T, INFER,这三个分别是什么意思啊，执行顺序是什么
> 2. 我试了I T 都跑不通会报错。config。yaml task: I 报错：
>    ![image](https://user-images.githubusercontent.com/5687816/273486980-aba7f054-f6c1-4a3a-8986-ad1befc4807b.png)
>    task: T 报错
>    ![image](https://user-images.githubusercontent.com/5687816/273487077-3d2b8d58-63f7-4bb5-983c-186b5ede4230.png)
>    好像少了一个文件啊，这个不是checkpoint吗 我第一次运行为什么需要这个

**Comment by sh308178685** [comment]
![image](https://github.com/foocker/F2P/assets/5687816/0f35b8fc-71cf-4d6d-92e6-a909b0886edf)
task:infer 报错。。

**Comment by foocker** [comment]
> ![image](https://user-images.githubusercontent.com/5687816/273487399-0f35b8fc-71cf-4d6d-92e6-a909b0886edf.png) task:infer 报错。。

这个你看下代码，很容易就懂了。 run.py中，Infer是推理，肯定是先训练了，有了模型，才能推理。然后是训练，分I和T，这个在solover/trainer.py中能看到，I是Imitator。Imitator具体含义你可以看下论文，然后T是在Imitator训练后的基础上，训练其他模块。所以，是先I后T后Infer。

**Comment by sh308178685** [comment]
> > ![image](https://user-images.githubusercontent.com/5687816/273487399-0f35b8fc-71cf-4d6d-92e6-a909b0886edf.png) task:infer 报错。。
> 
> 这可以看下代码。 run.py中，Infer是推理，肯定是先训练了，有了模型，才能推理。然后是训练，分I和T，这个在solover/trainer.py中能看到，I是Imitator。Imitator具体含义你可以看下论文(在配置文件中我也写了，是一个生成模型，其他参数怎么选，配置文件中都写了说明)，然后T是在Imitator训练后的基础上，训练其他模块。所以，是先I后T后Infer。 最佳路线是先看论文，然后看代码，最后做实验。

谢谢 还有就是为啥第一次训练 需要CHECKPOINT呢 然后因为没有CHECKPOINT 报错了

**Comment by sh308178685** [comment]
> > ![image](https://user-images.githubusercontent.com/5687816/273487399-0f35b8fc-71cf-4d6d-92e6-a909b0886edf.png) task:infer 报错。。
> 
> 这可以看下代码。 run.py中，Infer是推理，肯定是先训练了，有了模型，才能推理。然后是训练，分I和T，这个在solover/trainer.py中能看到，I是Imitator。Imitator具体含义你可以看下论文(在配置文件中我也写了，是一个生成模型，其他参数怎么选，配置文件中都写了说明)，然后T是在Imitator训练后的基础上，训练其他模块。所以，是先I后T后Infer。 最佳路线是先看论文，然后看代码，最后做实验。

not exist checkpoint of imitator with path ./output/checkpoints/Imitator/Imitator_130_tagII.pth     就是这个文件 这个是哪里来的啊

**Comment by sh308178685** [comment]
cfg里面 我把finetune改成了false ，epoch改成了500 可以运行了，然后过了一会报错参数个数不一致，我的参数有223个，我看到CFG文件里面 # Translator
mode: "train" # train, test
params_cnt: 28
embeding_dim: 256
projection_reduce: False
cn: 28
dn: 0      params_cnt 和 cn 是否都需要改成223

**Comment by foocker** [comment]
> cfg里面 我把finetune改成了false ，epoch改成了500 可以运行了，然后过了一会报错参数个数不一致，我的参数有223个，我看到CFG文件里面 # Translator mode: "train" # train, test params_cnt: 28 embeding_dim: 256 projection_reduce: False cn: 28 dn: 0 params_cnt 和 cn 是否都需要改成223

忘了，应该是。看下代码。

**Comment by sh308178685** [comment]
我训练了两次，第一次我的参数数据集 最大值最小值都是固定的-100 和 100 ，训练成功之后，效果不是很理想，生成的图片都是乱七八糟的。 第二次我每个参数的最大值最小值都不同，但是训练之后，不管我传入的是什么样本参数，输出的图片都是同一张人脸 什么鬼啊 求指导

**Comment by sh308178685** [comment]
> 我训练了两次，第一次我的参数数据集 最大值最小值都是固定的-100 和 100 ，训练成功之后，效果不是很理想，生成的图片都是乱七八糟的。 第二次我每个参数的最大值最小值都不同，但是训练之后，不管我传入的是什么样本参数，输出的图片都是同一张人脸 什么鬼啊 求指导

我说的是我训练好的IMITATOR

**Comment by foocker** [comment]
> 我训练了两次，第一次我的参数数据集 最大值最小值都是固定的-100 和 100 ，训练成功之后，效果不是很理想，生成的图片都是乱七八糟的。 第二次我每个参数的最大值最小值都不同，但是训练之后，不管我传入的是什么样本参数，输出的图片都是同一张人脸 什么鬼啊 求指导

参数做min-max归一化处理。过拟合了吧，检查下判别器。提高生成数据的分布，可以加一个条件，一个数或者一个固定的张量。
