### ISSUE TITLE
测试集生成出的人脸完全不像啊

### ISSUE THREAD

**Issue by lirui991225** [foocker/F2P#6]
用余弦退火加余弦学习率训练了500epochs，已经收敛了，验证集l1损失也下降到了最低趋于稳定，但是在测试集上infer生成图像和原图完全不像，并且反卷积网络的梯度分布图和权重分布图只有最后一层和BN层在变化，反卷积的参数值和梯度根本没变，卷积核只有偏置在更新，变化比较明显，呈现均匀分布

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/934128a0-64b7-499c-8465-6abbd8a7a1b2)

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/c25eaa61-ab21-46c1-b177-165c34466079)

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/e8160490-15cb-49c4-8e62-d5389beaa0d5)

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/2ab09139-3c80-4145-80a6-50b1b7a32195)

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/56cf18ce-bd0b-420a-bf67-f0eb783361fc)
这是测试结果

**Comment by lirui991225** [comment]
我们的数据集里混合了骨骼和morph target，一共有262个参数

**Comment by lirui991225** [comment]
ctt的损失怎么这样啊
![image](https://github.com/foocker/F2P/assets/56287874/a6377166-ea65-43d5-8fe1-13aa22f5203d)

**Comment by foocker** [comment]
> 用余弦退火加余弦学习率训练了500epochs，已经收敛了，验证集l1损失也下降到了最低趋于稳定，但是在测试集上infer生成图像和原图完全不像，并且反卷积网络的梯度分布图和权重分布图只有最后一层和BN层在变化，反卷积的参数值和梯度根本没变，卷积核只有偏置在更新，变化比较明显，呈现均匀分布

你可以一步一步验证下（embeding是否有差异，embeding后的face_parameters是否有差异，单独生成模块是否有效果），原始论文v2其实用了v1的模型先验，我这里没有用；其次原文有离散参数，分类这块，我这里写了pass，原始对连续变量做了降维分解，我也没做；最后，你这里的情况表明，根本没学会embeding->face_parameters。ctt的损失确实奇怪，我之前也是这样，讲道理，这个分割网络在原始论文中是需要重新训练的，我只是用了一个人脸的分割网络，我测试过，在动画数据上效果不太好，另外，这里的损失其实有点”战线太长”的感觉。
题外话，久了，忘了。人脸识别的embeding对同id角色，只是脸表情不同，未必具有可分性（这点很容易分析，同id,不同表情，embeding矩阵，算下cov_similary看看区别度如何），这点对原始论文存疑，搞一个各种id，各种表情，各种离散特征的数据集，做一个clip可能会更优说服力。另外，也可以找和表情相关的3d人脸重建算法来抽取特征，也是个合理的方法。

**Comment by lirui991225** [comment]
可以给个联系方式一起交流学习吗，cv爱好者

**Comment by foocker** [comment]
> 可以给个联系方式一起交流学习吗，cv爱好者

你去wav2lip的git看看，可以加那个群。或者qq群324090058试试看

**Comment by lirui991225** [comment]
白化的投影变换乘原数据还是去中心化的数据呢，需要一开始就把数据去中心化吗，然后再求协方差矩阵，还是直接用原始数据求协方差矩阵的特征向量，然后乘原始数据

**Comment by foocker** [comment]
> 白化的投影变换乘原数据还是去中心化的数据呢，需要一开始就把数据去中心化吗，然后再求协方差矩阵，还是直接用原始数据求协方差矩阵的特征向量，然后乘原始数据

都试试吧，论文这块没说清楚。不去中心化，至少有的量纲一致吧，否则梯度浮动大了也不行。

**Comment by lirui991225** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月26日(星期天) 上午8:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [foocker/F2P] 测试集生成出的人脸完全不像啊 (Issue #6)





  
白化的投影变换乘原数据还是去中心化的数据呢，需要一开始就把数据去中心化吗，然后再求协方差矩阵，还是直接用原始数据求协方差矩阵的特征向量，然后乘原始数据
  
都试试吧，论文这块没说清楚。不去中心化，至少有的量纲一致吧，否则梯度浮动大了也不行。

**Comment by lirui991225** [comment]
请问为啥在eval模式下输出都是一样的，把bn层的trackrunningstates改为false就eval和train模式一样了，但是测试batch只能大于等于2，输入batch为1的时候会报错说应该是bn层在计算没用runningmean    报错：Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

**Comment by foocker** [comment]
> 请问为啥在eval模式下输出都是一样的，把bn层的trackrunningstates改为false就eval和train模式一样了，但是测试batch只能大于等于2，输入batch为1的时候会报错说应该是bn层在计算没用runningmean 报错：Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

```
    训练模式 (train):
        track_running_stats=True：在训练模式下，BN 层将使用当前的 mini-batch 统计信息进行归一化。每个 mini-batch 的均值和方差将被用于归一化该 mini-batch 的输入。
        track_running_stats=False：在训练模式下，BN 层将使用当前 mini-batch 的统计信息进行归一化，并且还会更新 BN 层内部维护的全局均值和方差。这些全局统计信息在推理（evaluation）时用于规范化输入。

    推理模式 (eval):
        track_running_stats=True：在推理模式下，BN 层将使用先前训练阶段累积的全局均值和方差进行规范化。这确保了在推理阶段输入的规范化与训练阶段一致。
        track_running_stats=False：在推理模式下，BN 层将使用先前训练阶段累积的全局均值和方差进行规范化，但不会再更新这些全局统计信息。
```

**Comment by lirui991225** [comment]
![image](https://github.com/foocker/F2P/assets/56287874/e20ad10a-61d8-4218-9a36-001764be339d)

**Comment by lirui991225** [comment]
还是测试模式一直这样输出不变

**Comment by lirui991225** [comment]
是这个bn1d的原因应该

**Comment by foocker** [comment]
> 是这个bn1d的原因应该

具体哪里？
