### ISSUE TITLE
您好，小白对该项目有诸多疑问，想向您请教，方便的话可否加您一下联系方式？（qq：1810578934）

### ISSUE THREAD

**Issue by B-ON111** [foocker/F2P#9]
您好，小白对该项目有诸多疑问，想向您请教，方便的话可否加您一下联系方式？（qq：1810578934）

**Comment by foocker** [comment]
> 您好，小白对该项目有诸多疑问，想向您请教，方便的话可否加您一下联系方式？（qq：1810578934）

项目依赖引擎+数据，算法这块，也没做充分的验证。
